package:
  name: databroker
  version: 0.4.1

source:
  git_url: https://github.com/NSLS-II/databroker
  git_rev: v0.4.1

build:
  number: 0

requirements:
  build:
    - python
  run:
    - boltons
    - channelarchiver  # Not actually used in this project...
    - cytoolz
    - doct
    - filestore >=0.3.0
    # - h5py  # h5py is a dep in databroker/examples/hdf_io.py
    - metadatastore >=0.5.1
    - numpy
    - pandas
    - pims
    - python
    - pytz
    - six
    - requests
    - singledispatch [py27]
    - tzlocal

test:
  requires:
    - nslsii_dev_configuration
  commands:
    - source activate $PREFIX && python -c "import databroker"

about:
  home: https://github.com/NSLS-II/databroker
  license: BSD
