{% set version = "0.0.3" %}

package:
  name: srw
  version: {{ version }}

source:
  git_url: https://github.com/ochubar/SRW
  git_rev: d6c5f7ebfea3954e0863755209b4b249355c59c3

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - python

  run:
    - matplotlib
    - numpy
    - python
    - scipy

test:
  imports:
    - srwl_bl
    - srwlib
    - srwlpy

about:
  home: https://github.com/ochubar/SRW
  license: Custom
  license_url: https://github.com/ochubar/SRW/blob/master/COPYRIGHT.txt
  summary: Synchrotron Radiation Workshop

extra:
  recipe-maintainers:
    - mrakitin
