{% set year = "2018" %}
{% set cycle = "1" %}
{% set version = "0" %}

package:
  name: 23-id-2-csx2-analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - csxtools
    - amostra
