{% set version = "0.5.0" %}
package:
  name: suitcase
  version: {{ version }}

source:
  url: https://github.com/NSLS-II/suitcase/archive/v{{ version }}.tar.gz
  fn: suitcase-v{{ version }}.tar.gz
  sha256: 50c1f832fa4d8728bcf3674a5a32c4911daf7223cf7004f93ac1d2eee205ecfc

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python

  run:
    - databroker
    - h5py
    - metadatastore
    - numpy
    - python

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - suitcase

about:
  home: https://github.com/nsls-ii/suitcase
  license:  BSD 3-Clause
  summary: data export facilities for NSLS-II

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
