{% set version = "5.0.0.2080" %}

package:
    name: hkl
    version: {{ version }}

source:
    git_url: https://github.com/picca/hkl
    git_rev: v{{ version }}

build:
    number: 2
    skip: True  # [py2k]

requirements:
    build:
        - autoconf
        - automake
        - gobject-introspection
        - gsl
        - libtool
        - m4
        - pkg-config
        - pygobject  # [py2k]
        - pygobject3  # [py3k]
        - python
    run:
        - numpy
        - pygobject  # [py2k]
        - pygobject3  # [py3k]
        - python
        - gsl
        - pcre
        - libiconv
about:
    home: http://repo.or.cz/w/hkl.git/
    license: LGPL
