{% set version = "1.0.14" %}
package:
  name: pysmbc
  version: {{ version }}

source:
  git_url: https://github.com/hamano/pysmbc.git
  git_rev: {{ version }}

build:
  number: 1
  script: python setup.py install

requirements:
  build:
    - python
    - xattr
  run:
    - python
    - xattr

test:
  imports:
    - smbc
