{% set version = "1.11.0" %}

package:
    name: lightflow
    version: {{ version }}

source:
    git_url: https://github.com/australiansynchrotron/lightflow
    git_rev: v{{ version }}

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
        - numpy
    run:
        - python
        - numpy
        - celery >=4.0.2
        - click >=6.7
        - colorlog >=2.10.0
        - networkx
        - pymongo >=3.6.0
        - pytz >=2016.10
        - redis-py >=2.10.5
        - ruamel.yaml >=0.14.2
        - cloudpickle >=0.2.2

test:
    imports:
        - lightflow

about:
    home: http://australiansynchrotron.github.io/lightflow/
    license: BSD 3-Clause
    summary: Lightflow is a Python 3.5+ library and command-line tool for
        executing workflows, composed of individual tasks, in a distributed
        fashion. It is based on Celery and provides task dependencies, data
        exchange between tasks and an intuitive description of workflows.
    license_family: BSD
