package:
  name: tzlocal
  version: 1.1.2

source:
  git_rev: 1.1.2
  git_url: https://github.com/regebro/tzlocal

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - pytz

  run:
    - python
    - pytz

test:
  imports:
    - tzlocal

about:
  home: https://github.com/regebro/tzlocal
  license: CC0 1.0 Universal
  summary: 'tzinfo object for the local timezone'
