{% set version = "1.14" %}
package:
  name: automake
  version: {{ version }}

source:
  fn: automake-{{ version }}.tar.gz
  url: http://ftp.gnu.org/gnu/automake/automake-{{ version }}.tar.gz
  sha256: 7847424d4204d1627c129e9c15b81e145836afa2a1bf9003ffe10aa26ea75755

build:
  number: 3
  skip: True  # [not linux]

requirements:
  build:
    - m4
    - autoconf
  run:
    - m4
    - autoconf
test:
  commands:
    - automake --help

about:
  home: http://www.gnu.org/software/automake/
  license: GPL 3
