package:
  name: clint
  version: 0.5.1

source:
  git_url: http://github.com/kennethreitz/clint
  git_rev: v0.5.1

build:
  number: 1
requirements:
  build:
    - python
    - pip
    - args

  run:
    - python
    - args

test:
  imports:
    - clint

about:
  home: http://github.com/kennethreitz/clint
  license: ISC
  summary: Python Command-line Application Tools
