package:
  name: databroker
  version: {{ environ.GIT_DESCRIBE_TAG[1:] }}.post{{ environ.GIT_DESCRIBE_NUMBER }}

source:
  git_url: https://github.com/NSLS-II/databroker
  git_rev: master

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python
    - setuptools
  run:
    - attrs
    - boltons
    - cytoolz
    - doct
    - filestore >=0.5.0
    - metadatastore >=0.5.1
    - pandas
    - pims
    - python
    - requests
    - singledispatch [py27]
    - six
    - tzlocal

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - databroker

about:
  home: https://github.com/NSLS-II/databroker
  license: BSD

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
