package:
  name: databroker
  version: {{ environ.GIT_DESCRIBE_TAG[1:] }}.post{{ environ.GIT_DESCRIBE_NUMBER }}

source:
  git_url: https://github.com/NSLS-II/databroker
  git_rev: master

build:
  number: 3
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python
    - setuptools
  run:
    - attrs >=16.3.0
    - boltons
    - cytoolz
    - doct
    - glueviz
    - h5py
    - humanize
    - jsonschema
    - jinja2
    - mongoquery
    - numpy
    - pandas
    - pims
    - pymongo
    - python
    - pytz
    - pyyaml
    - requests
    - singledispatch [py27]
    - six
    - tifffile
    - tornado
    - tzlocal
    - ujson

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - databroker

about:
  home: https://github.com/NSLS-II/databroker
  license: BSD

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
