{% set version = "0.3.0" %}

package:
    name: ophyd
    version: {{ version }}

source:
    url: https://github.com/NSLS-II/ophyd/archive/v{{ version }}.tar.gz
    fn: ophyd-v{{ version }}.tar.gz
    sha256: f91c4726cb5f9ac6caeca03fe1722a51a92ae504fff7fc230c9b5dc16479e678

build:
    number: 1
    skip: True  # [py2k]
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - filestore
        - ipython
        - networkx
        - prettytable
        - pyepics
        - python

test:
    imports:
        - ophyd

about:
    home: https://github.com/NSLS-II/ophyd
    license: BSD 3-Clause
