package:
  name: filestore
  version: '0.1.0'

source:
  git_url: https://github.com/NSLS-II/filestore.git
  git_rev: 'v0.1.0'
  patches:
    - config.patch

build:
  number: 1


requirements:
  build:
    - python
    - six

  run:
    - python
    - mongoengine ==0.8.7
    - h5py
    - numpy
    - six
    - pyyaml
    - jsonschema
    - pims
    - tifffile
    - boltons

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - filestore
    - filestore.api
    - filestore.commands
    - filestore.conf
    - filestore.file_writers
    - filestore.handlers
    - filestore.odm_templates
    - filestore.retrieve
    - filestore.utils

about:
  home: http://github.com/NSLS-II/filestore
  license: BSD
