{% set name = "oscars" %}
{% set version = "2.0.4" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: https://github.com/dhidas/{{ name }}
  git_rev: {{ version }}


build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - scipy
    - matplotlib
    - mpi4py
    - numpy
    - python
    - scipy
    
test:
  imports:
    - oscars.sr
    - oscars.plots_mpl

about:
  home: http://oscars.bnl.gov/
  license: LICENSE.txt
  license_family: OTHER
  license_file: ''
  summary: Open Source Code for Advanced Radiation Simulation
  description: The OSCARS Package.
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
