{% set version = "2.0.0" %}
package:
    name: eiger-io
    version: {{ version }}

source:
    url: https://github.com/NSLS-II-CHX/eiger-io/archive/v{{ version }}.tar.gz
    fn: eiger-io-v{{ version }}.tar.gz

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools

    run:
        - filestore
        - h5py
        - numpy
        - pims
        - python
        - six

test:
    requires:
        - nslsii_dev_configuration
    imports:
        - eiger_io

about:
    home: https://github.com/NSLS-II-CHX/eiger-io
    license: BSD
