{% set version = "2.0.2" %}
package:
    name: eiger-io
    version: {{ version }}

source:
    git_url: https://github.com/NSLS-II/eiger-io
    git_rev: v{{ version }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools

    run:
        - h5py
        - numpy
        - pims
        - python
        - six
        - hdf5-lz4

test:
    requires:
        - nslsii_dev_configuration
    imports:
        - eiger_io

about:
    home: https://github.com/NSLS-II/eiger-io
    license: BSD
