package:
  name: boltons
  version: 15.0.0

source:
  git_url: http://github.com/mahmoud/boltons.git
  git_rev: 15.0.0

build:
  number: 0


requirements:
  build:
    - python
    - pytest

  run:
    - python

test:
  imports:
    - boltons
