{% set version = "1.0.2" %}

package:
  name: doct
  version: {{ version }}

source:
  url: https://github.com/NSLS-II/doct/archive/v{{ version }}.tar.gz
  fn: doct-v{{ version }}.tar.gz
  sha256: 77e12fe268ea4591d5d90b363aa7cbc1a0e5c2d248ef8c7fa8b499fff0629c25

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - humanize
    - prettytable
    - python
    - six

  run:
    - humanize
    - prettytable
    - python
    - six

test:
  imports:
    - doct

about:
  home: https://github.com/NSLS-II/document
  license: BSD
