package:
  name: doct
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: https://github.com/NSLS-II/doct
  git_rev: master

build:
  number: 0

  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}


requirements:
  build:
    - python
    - six

  run:
    - python
    - six
    - humanize
    - prettytable

test:
  imports:
    # Import all the packages
    - doct

about:
  home: https://github.com/NSLS-II/document
  license: BSD
