{% set year = "2018" %}
{% set cycle = "3" %}
{% set version ="0" %}

package:
  name: 08-id-iss-collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - isstools
    - lightflow
    - netcdf4
    - xraylarch
