package:
  name: pymongo
  version: 2.9.1

source:
  git_url: http://github.com/mongodb/mongo-python-driver
  git_rev: 2.9.1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - bson
    - gridfs
    - pymongo

about:
  home: http://github.com/mongodb/mongo-python-driver
  license: Apache Software License
  summary: 'Python driver for MongoDB <http://www.mongodb.org>'

