package:
  name: pyspec
  version: 0.2.0

source:
  # this is sort of janky recipe since @stuwilkins has no tags on pyspec
  git_url: https://github.com/stuwilkins/pyspec.git
  git_rev: 7300a7f9753f28b504ce5e2dab9c0762a6b36008

build:
  number: 0

requirements:
  build:
    - setuptools
    - python
    - numpy
    - scipy
    - matplotlib

  run:
    - python
    - numpy
    - scipy
    - matplotlib

test:
  # Python imports
  imports:
    - pyspec
    - pyspec.fit
    - pyspec.fitfuncs

about:
  home: https://github.com/stuwilkins/pyspec
  license: GPL

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
