{% set year = "17" %}
{% set cycle = "Q1" %}
{% set version ="0" %}

package:
  name: collection
  version: {{ year }}{{ cycle }}.{{ version }}

build:
  number: 1

requirements:
  run:
    - analysis >=17Q1.0
    - ophyd ==0.4.0
    - pyepics ==3.2.6
    - pyolog ==4.1.0
