{% set year = "18" %}
{% set cycle = "Q1" %}
{% set version ="0" %}

package:
  name: collection
  version: {{ year }}{{ cycle }}.{{ version }}

build:
  number: 2

requirements:
  run:
    - analysis
    - ophyd
    - pyepics
    - pyolog
