{% set year = "2017" %}
{% set cycle = "01" %}
{% set version ="0" %}

package:
  name: collection
  version: {{ year }}_{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - analysis >=2017_01.0
    - ophyd ==0.4.0
    - pyepics ==3.2.6
    - pyolog ==4.1.0
    - pyqt ==4.11
