{% set year = "17" %}
{% set cycle = "Q3" %}
{% set version ="0" %}

package:
  name: collection
  version: {{ year }}{{ cycle }}.{{ version }}

build:
  number: 1

requirements:
  run:
    - analysis
    - ophyd
    - pyepics
    - pyolog
