{% set year = "2017" %}
{% set cycle = "01" %}

package:
  name: collection
  version: {{ year }}_{{ cycle }}

build:
  number: 0

requirements:
  run:
    - analysis >=2017_01
    - bluesky
    - ophyd
    - pyolog
