{% set year = "17" %}
{% set cycle = "Q2" %}
{% set version ="0" %}

package:
  name: collection
  version: {{ year }}{{ cycle }}.{{ version }}

build:
  number: 2

requirements:
  run:
    - analysis >=17Q2.0
    - ophyd ==0.6.1
    - pyepics ==3.2.6
    - pyolog ==4.2.0
