{% set year = "2018" %}
{% set cycle = "2" %}
{% set version ="0" %}

package:
  name: collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - analysis
    - caproto
    - ophyd
    - pyepics
    - pyolog
    - pyserial
