{% set year = "18" %}
{% set cycle = "C2" %}
{% set version ="0" %}

package:
  name: 03-id-hxn-collection
  version: {{ year }}{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - hxnfly >=0.0.2
    - hxntools  >=0.0.4
    - tqdm
    - ppmac
    - pypdf2
    - reportlab
