package:
  name: suitcase
  version: {{ environ.get('GIT_DESCRIBE_TAG')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER') }}

source:
  git_url: https://github.com/NSLS-II/suitcase.git
  git_rev: master

build:
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six
    - databroker
    - h5py
    - numpy

test:
  requires:
    - nslsii_dev_configuration

  imports:
    - suitcase
