package:
  name: pcaspy
  version: 0.5.1.post17

source:
  git_url: https://github.com/paulscherrerinstitute/pcaspy
  git_rev: 0.5.1-17-g05ec8a9

build:
  number: 0
  string: {{ environ['CONDA_BUILD'] }}_g05ec8a9_py{{ py }}

requirements:
  build:
    - python
    - setuptools
    - epics-base
    - swig

  run:
    - python
    - epics-base

test:
  imports:
    - pcaspy

about:
  home: https://code.google.com/p/pcaspy/
  license: BSD
