package:
  name: prettytable
  version: 0.7.2

source:
  git_url: https://github.com/lmaurits/prettytable.git
  git_rev: 0.7.2-RELEASE
requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - prettytable

about:
  home: http://github.com/lmaurits/prettytable/
  license: BSD License
  summary: 'A simple Python library for easily displaying tabular data in a visually appealing ASCII table format'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
