package:
  name: metadatastore
  version: '0.1.0'

source:
  git_url: http://github.com/NSLS-II/metadatastore.git
  git_rev: 'v0.1.0'
  patches:
    - config.patch

build:
  number: 0

  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}_np{{ np }}py{{ py }}


requirements:
  build:
    - python
    - six

  run:
    - python
    - mongoengine ==0.8.7
    - six
    - pyyaml
    - prettytable
    - humanize
    - numpy
    - pytz

test:
  requires:
    - nslsii_dev_configuration

  # Python imports
  imports:
    - metadatastore
    - metadatastore.commands
    - metadatastore.api
    - metadatastore.conf
    - metadatastore.odm_templates
    - metadatastore.document
    - metadatastore.utils

about:
  home: http://github.com/NSLS-II/metadatastore
  license: BSD
