package:
  name: conda-build
  version: 1.19.0


source:
  git_url: https://github.com/conda/conda-build
  git_rev: 1.19.0

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python
    - conda
    - jinja2
    - patchelf      [linux]

test:
  commands:
    - conda-build -h
  imports:
    - conda_build

about:
  home: https://github.com/conda/conda-build
  license: BSD
