package:
    name: ophyd
    version: {{ environ.GIT_DESCRIBE_TAG }}.post{{ environ.GIT_DESCRIBE_NUMBER }}

source:
    git_url: https://github.com/NSLS-II/ophyd.git
    git_rev: master

build:
  number: 0
  skip: True  # [py2k]
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - filestore
    - ipython
    - networkx
    - numpy
    - prettytable
    - pyepics
    - python

test:
  # only need to import the subpackages
  imports:
    - ophyd
    - ophyd.utils
    - ophyd.areadetector

about:
  home: https://github.com/NSLS-II/ophyd
  license: BSD 3-Clause

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
