
package:
    name: characteristic
    version: 14.3.0

source:
    git_url: https://github.com/hynek/characteristic/
    git_rev: 14.3.0

build:
    number: 0

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - characteristic

about:
    home: http://characteristic.rtfd.org/
    license: MIT
    summary: Python attributes without boilerplate
