package:
  name: pyxrf
  version: 0.0.3

source:
  git_url: https://github.com/NSLS-II/pyxrf
  git_rev: v0.0.3

build:
  number: 0
  string: py{{ py }}_{{ environ['CONDA_BUILD'] }}
  entry_points:
    - pyxrf = pyxrf.gui:run

requirements:
  build:
    - python <3
    - numpy
    - enaml
    - setuptools

  run:
    - python <3
    - enaml
    - h5py
    - matplotlib
    - numpy
    - pandas
    - scikit-beam

about:
  home: https://github.com/NSLS-II/pyxrf
  license: 3-Clause BSD
