package:
  name: boltons
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: https://github.com/mahmoud/boltons.git
  git_rev: master

build:
  number: 1
  string: {{ environ['GIT_BUILD_STR'] }}_py{{ py }}


requirements:
  build:
    - python
    - pytest

  run:
    - python

test:
  imports:
    - boltons
