package:
  name: boltons
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'GIT_STUB') }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 'inf') }}

source:
  git_url: https://github.com/mahmoud/boltons.git
  git_rev: master

build:
  number: 1
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}


requirements:
  build:
    - python
    - pytest

  run:
    - python

test:
  imports:
    - boltons
