package:
  name: pymongo
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'GIT_STUB') }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 'GIT_STUB') }}

source:
  git_url: https://github.com/mongodb/mongo-python-driver
  git_rev: master

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}_py{{ py }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - bson
    - pymongo
    - gridfs

about:
  home: http://github.com/mongodb/mongo-python-driver
  license: Apache Software License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
