package:
    name: lmfit
    version: 0.9.0

source:
    git_url: http://github.com/lmfit/lmfit-py.git
    git_tag : 0.9.0

build:
    number: 0

requirements:
    build:
        - python
        - numpy
        - scipy

    run:
        - python
        - numpy
        - scipy
        - ipython
        - ipywidgets
        - pandas
        - matplotlib

test:
    imports:
        - lmfit

about:
    home: http://lmfit.github.io/lmfit-py/
    license: BSD
