package:
  name: channelarchiver
  version: {{ environ.GIT_DESCRIBE_TAG }}.post{{ environ.GIT_DESCRIBE_NUMBER }}

source:
  git_url: https://github.com/NSLS-II/channelarchiver
  git_rev: master

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - setuptools
    - python
    - numpy
    - matplotlib
    - tzlocal

  run:
    - python
    - numpy
    - matplotlib
    - tzlocal

test:
  imports:
    - channelarchiver

about:
  home: https://github.com/NSLS-II/channelarchiver
  license: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
