{% set version = "5.0.0.2173" %}

package:
    name: hkl
    version: {{ version }}

source:
    git_url: https://github.com/picca/hkl
    git_rev: v{{ version }}

build:
    number: 4
    skip: True  # [py2k]

requirements:
    build:
        - autoconf
        - automake
        - gobject-introspection
        - pygobject3 ==3.18.2
        - gsl ==2.2.1
        - libtool
        - m4
        - pkg-config
          #- pygobject  # [py2k]
          #- pygobject3  # [py3k]
        - python
    run:
        - numpy
          #- pygobject  # [py2k]
        - pygobject3 ==3.18.2  # [py3k]
        - python
        - gsl ==2.2.1
        - pcre
        - libiconv
about:
    home: http://repo.or.cz/w/hkl.git/
    license: LGPL
