package:
  name: pims
  version: 0.2.2

source:
  git_url: https://github.com/soft-matter/pims
  git_tag: v0.2.2

build:
  binary_relocation: true


requirements:
  build:
    - python
    - setuptools
    - six
    - numpy
    - scikit-image  # one of { scikit-image | matplotlib | scipy }
    - tifffile

  run:
    - python
    - six >=1.8
    - numpy >=1.7
    - scikit-image  # one of { scikit-image | matplotlib | scipy }
    - tifffile >=0.3.1
    - pillow  # optional, but necessary for ipython rich display

test:
  imports:
    - pims


about:
  home: http://github.com/soft-matter/pims
  license: 3-clause BSD License
  summary: 'Python particle-tracking toolkit'
