{% set version = "2.5.0" %}

package:
  name: git
  version: {{ version }}

source:
  url: https://github.com/git/git/archive/v{{ version }}.tar.gz
  fn: git-{{ version }}.tar.gz
  sha256: 31ebd4f35b5b941a5ac51c01ecb211911650b834a4085878e854cce59a470424

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - openssl
    - zlib
    - curl
    - gettext
  run:
    - openssl
    - zlib
    - curl

test:
  commands:
    - git --version

about:
  home: http://git-scm.com/
  license: GPL v2 and LGPL 2.1
  summary: distributed version control system
