{% set name = "pypdf2" %}
{% set version = "1.26.0" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    git_url: https://github.com/mstamy2/PyPDF2
    git_rev: {{ version }}

build:
    number: 0
    script: python setup.py install
    skip: True  # [win]

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - PyPDF2
        - PyPDF2.pdf

about:
    home: http://mstamy2.github.io/PyPDF2/
    license: Custom
    license_url: https://github.com/mstamy2/PyPDF2/blob/master/LICENSE
    summary: A utility to read and write PDFs with Python

extra:
    recipe-maintainers:
        - mrakitin
