{% set version = "1.3" %}

package:
  name: isstools
  version: {{ version }}

source:
  git_url: https://github.com/NSLS-II-ISS/isstools
  git_rev: v{{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - six

  run:
    - numpy
    - scipy
    - matplotlib
    - pyqt 4*
    - bluesky
    - pexpect
    - pysmbc
    - netcdf4
    - pyparsing
test:
  imports:
    - isstools

about:
  home: https://github.com/NSLS-II-ISS/isstools 
  license: BSD
