package:
  name: filestore
  version: {{ environ.get('GIT_DESCRIBE_TAG')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER') }}

source:
  git_url: https://github.com/NSLS-II/filestore
  git_rev: master
  patches:
    - config.patch

build:
  number: 1

requirements:
  build:
    - python
    - six

  run:
    - python
    - h5py
    - six
    - pyyaml
    - jsonschema
    - pims
    - tifffile
    - boltons
    - pymongo
    - doct

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - filestore
    - filestore.api
    - filestore.conf
    - filestore.file_writers
    - filestore.handlers

about:
  home: https://github.com/NSLS-II/filestore
  license: BSD
