{% set version = "1.2.0" %}

package:
  name: historydict
  version: {{ version }}

source:
    git_url: https://github.com/Nikea/historydict
    git_rev: v{{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six

test:
  imports:
    - historydict

about:
  home: https://github.com/Nikea/historydict
  license: BSD 3-Clause

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
