package:
    name: hdf5-lz4
    version: {{ environ.get('GIT_DESCRIBE_TAG', 'GIT_STUB') }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 'GIT_STUB') }}

source:
    git_url: https://github.com/dectris/HDF5Plugin.git
    git_tag: master

build:
    number: 1

requirements:
    build:
        - hdf5
    run:
        - hdf5
        - conda-env >2.1.4  # when $CONDA_ENV_PATH was added

about:
    home: https://github.com/dectris/HDF5Plugin
    license: BSD-2
