package:
    name: hdf5-lz4
    version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
    git_url: https://github.com/dectris/HDF5Plugin.git
    git_tag: master

build:
    number: 1

requirements:
    build:
        - hdf5
    run:
        - hdf5
        - conda-env >2.1.4  # when $CONDA_ENV_PATH was added

about:
    home: https://github.com/dectris/HDF5Plugin
    license: BSD-2
