package:
  name: pyxrf
  version: {{ environ.GIT_DESCRIBE_TAG[1:] }}.post{{ environ.GIT_DESCRIBE_NUMBER }}

source:
  git_url: https://github.com/NSLS-II/pyxrf
  git_rev: master

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - pyxrf = pyxrf.gui:run

requirements:
  build:
    - python
    - setuptools

  run:
    - atom
    - enaml
    - h5py
    - ipywidgets
    - jupyter
    - matplotlib
    - numpy
    - pandas
    - pillow
    - python
    - scipy
    - six
    - scikit-beam
    - scikit-image

test:
  imports:
    - pyxrf

about:
  home: https://github.com/NSLS-II/pyxrf
  license: 3-Clause BSD

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
