package:
    name: hxnfly
    version: 0.0.1

source:
    hg_url: https://code.nsls2.bnl.gov/hg/xf/03id/python/hxnfly
    hg_tag: tip


build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    skip: True   # [py2k]

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - ophyd
        - ppmac
        - ipython

test:
    imports:
        - hxnfly

about:
    home: https://nsls-ii.github.io/amostra
    license: BSD 3-Clause
    summary: "amostra is a collection of light-weight sample management classes"

extra:
    recipe-maintainers:
        - ericdill
        - tacaswell
        - licode
