package:
  name: ixstools
  version: 0.0.2

source:
  git_url: https://github.com/NSLS-II-IXS/ixstools
  git_rev: v0.0.2

build:
  number: 0
  entry_points:
    - align = ixstools.align:main

requirements:
  build:
    - python
  run:
    - python
    - lmfit
    - matplotlib
    - numpy
    - pandas
    - scipy
    - pyyaml

test:
  requires:
    - nose
    - coverage
  imports:
    - ixstools
    - ixstools.align
    - ixstools.fit
    - ixstools.io

about:
  home: http://scikit-beam.github.io/scikit-beam/
  license: 3-Clause BSD
