{% set version = "0.4.2" %}

package:
  name: hxntools
  version: {{ version }}

source:
  git_url: https://github.com/NSLS-II-HXN/hxntools
  git_rev: v{{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - six

  run:
    - bluesky
    - boltons
    - cycler
    - databroker >=0.11.1
    - h5py >=2.5.0
    - numpy
    - ophyd
    - pandas
    - pyepics
    - python
    - scipy


test:
  requires:
    - nslsii_dev_configuration
  imports:
    - hxntools

about:
  home: https://github.com/NSLS-II-HXN/hxntools
  license: BSD
