{% set version = "0.2.2" %}

package:
  name: hxntools
  version: {{ version }}

source:
  git_url: https://github.com/NSLS-II-HXN/hxntools
  git_rev: v{{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - six

  run:
    - numpy
    - filestore
    - h5py >=2.5.0
    - python

test:
  requires:
    - nslsii_dev_configuration

  imports:
    - hxntools
    - hxntools.detectors
    - hxntools.handlers

about:
  home: https://github.com/NSLS-II-HXN/hxntools
  license: BSD
