package:
  name: h5py
  version: 2.6.0

source:
  git_rev: 2.6.0
  git_url: https://github.com/h5py/h5py

requirements:
  build:
    - python
    - numpy
    - hdf5 >=1.10.0
    - cython
    - six
    - pkgconfig

  run:
    - python
    - numpy
    - hdf5 >=1.10.0
    - six
    - unittest2    #[py26]

about:
  home: http://www.h5py.org/
  license: New BSD (http://opensource.org/licenses/bsd-license.php)
