package:
  name: hgtools
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'GIT_STUB') }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 'inf') }}

source:
  git_url: https://github.com/jaraco/hgtools
  git_rev: master

build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - hgtools
    - hgtools.managers
    - hgtools.tests


about:
  home: https://github.com/jaraco/hgtools/
  license: GNU General Public License (GPL)
  summary: 'Classes and setuptools plugin for Mercurial repositories'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
