package:
  name: databroker
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/NSLS-II/databroker
  git_rev: master

build:
  number: 1


requirements:
  build:
    - python
  run:
    - boltons
    - channelarchiver  # Not actually used in this project...
    - cytoolz
    - doct
    - filestore >=0.2.0
    # - h5py  # h5py is a dep in databroker/examples/hdf_io.py
    - metadatastore >=0.3.1
    - pandas
    - pims
    - python
    - requests
    - singledispatch [py27]
    - six
    - tzlocal

test:
  requires:
    - nslsii_dev_configuration
    - h5py
  imports:
    - databroker
    - databroker.handler_registration
    - databroker.pims_readers
    - databroker.pivot
    - databroker.examples
    - databroker.examples.hdf_io
    - databroker.examples.sample_data
    - databroker.examples.sample_data.common_nonscalar
    - databroker.examples.sample_data.frame_generators
    - databroker.examples.sample_data.image_and_scalar
    - databroker.examples.sample_data.step_scan
    - databroker.utils
    - databroker.utils.diagnostics

about:
  home: https://github.com/NSLS-II/databroker
  license: BSD
