{% set version = "0.3.0" %}
package:
  name: trackpy
  version: {{ version }}

source:
  url: https://github.com/soft-matter/trackpy/archive/v{{ version }}.tar.gz
  fn: v{{ version }}.tar.gz
  sha256: 1b587a8b1b97484b1c85335593cdbd858dbea347a97678e7acb9404ee0e4fbcd

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.7
    - scipy >=0.12
    - six >=1.8
    - pandas >=0.12
    - pims
    - pyyaml
    - matplotlib

  run:
    - python
    - numpy >=1.7
    - scipy >=0.12
    - six >=1.8
    - pandas >=0.12
    - pims
    - pyyaml
    - matplotlib
    - numba >=0.13.4
    - numexpr  # required for pandas DataFrame.query, used in examples
    - pytables  # for pandas-based HDF5 code

test:
  imports:
    - trackpy

about:
  home: https://github.com/soft-matter/trackpy
  license: BSD
  summary: 'particle-tracking toolkit'

extra:
  recipe-maintainers:
    - danielballan
    - ericdill
    - licode
    - tacaswell
