package:
  name: atom
  version: {{ GIT_DESCRIBE_TAG }}.post{{ GIT_DESCRIBE_NUMBER }}

source:
  git_rev: master
  git_url: https://github.com/nucleic/atom
  patches:
   - setup.py.patch

build:
  # number: 0
  skip: True  # [py3k]

requirements:
  build:
    - python
    - setuptools
    - future

  run:
    - python

test:
  # Python imports
  imports:
    - atom
    - atom.datastructures
    - tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/nucleic/atom
  license: Modified BSD
  summary: 'Memory efficient Python objects'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
