package:
  name: pyxrf
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'GGIT_STUB')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 'GIT_STUB') }}

source:
  git_url: https://github.com/NSLS-II/pyxrf
  git_rev: master

build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}_py{{ py }}
  entry_points:
    - pyxrf = pyxrf.gui:run

requirements:
  build:
    - python
    - numpy
    - enaml
    - setuptools

  run:
    - python
    - enaml
    - h5py
    - matplotlib
    - numpy
    - pandas
    - scikit-beam

about:
  home: https://github.com/NSLS-II/pyxrf
  license: 3-Clause BSD
