package:
  name: pyxrf
  version: {{ environ.get('GIT_DESCRIBE_TAG')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER') }}

source:
  git_url: https://github.com/NSLS-II/pyxrf
  git_rev: master

build:
  number: 0
  entry_points:
    - pyxrf = pyxrf.gui:run

requirements:
  build:
    - python
    - numpy
    - enaml
    - setuptools

  run:
    - python
    - enaml
    - h5py
    - matplotlib
    - numpy
    - pandas
    - scikit-beam

about:
  home: https://github.com/NSLS-II/pyxrf
  license: 3-Clause BSD
