package:
  name: bluesky
  version: 0.2.2

source:
  git_url: https://github.com/NSLS-II/bluesky
  git_rev: v0.2.2

build:
  # Note that this will override the default build string with the Python
  # and NumPy versions
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - jsonschema
    - super_state_machine
    - numpy
    - metadatastore
    - filestore
    - matplotlib
    - prettytable
    - cycler
    - traitlets
    - history
    - lmfit

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - 'bluesky'
    - 'bluesky.examples'

about:
  home: https://github.com/NSLS-II/bluesky
  license: BSD
