package:
  name: slicerator
  version: 0.9.7

source:
  git_url: https://github.com/soft-matter/slicerator
  git_rev: v0.9.7

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - six
test:
  imports:
    - slicerator

about:
  home: https://github.com/soft-matter/slicerator
  license: BSD
  summary: 'A lazy-loading, fancy-sliceable iterable.'
