{% set version = "0.0.9" %}
package:
  name: scikit-beam
  version: {{ version }}

source:
  git_url: https://github.com/scikit-beam/scikit-beam
  git_rev: {{ version }}

build:
  number: 0
  # need the `python setup.py build_ext -i` line so that the test suite can be run.
  # it is advised to run the test suite since there is compiled code in here
  script: |
    python setup.py build_ext -i
    python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy
    - six
    - cython
  run:
    - lmfit ==0.8.3
    - numpy
    - python
    - scikit-image
    - scipy
    - six
    - xraylib [not win]

test:
  requires:
    - nose
    - coverage
  imports:
    - skbeam
  commands:
    - cd {{ environ.SRC_DIR }} && coverage run run_tests.py

about:
  home: http://scikit-xray.github.io/scikit-xray/
  license: 3-Clause BSD

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
