package:
  name: historydict
  version: {{ environ.GIT_DESCRIBE_TAG }}.post{{ environ.GIT_DESCRIBE_NUMBER }}

source:
  git_url: https://github.com/Nikea/historydict.git
  git_rev: master

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six

test:
  imports:
    - historydict

about:
  home: https://github.com/Nikea/historydict
  license: BSD 3-Clause

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
