{% set year = "2018" %}
{% set cycle = "1" %}
{% set version ="0" %}

package:
  name: 18-id-fxi-collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - tomopy
