{% set version = "0.6.2" %}

package:
  name: metadatastore
  version: {{ version }}

source:
  git_url: https://github.com/NSLS-II/metadatastore
  git_rev: v{{ version }}
  patches:
    - config.patch

build:
  number: 0
  script: |
    sed -i 's|__CONDA_BUILD_PLACEHOLDER__|'$PREFIX'/etc|' metadatastore/conf.py && \
    $PYTHON setup.py install --single-version-externally-managed --record=/dev/null


requirements:
  build:
    - python
    - six

  run:
    - doct
    - numpy
    - pymongo >=3.2
    - python
    - pytz
    - pyyaml
    - six

test:
  requires:
    - nslsii_dev_configuration

  imports:
    - metadatastore

about:
  home: https://github.com/NSLS-II/metadatastore
  license: BSD
