package:
  name: pims
  version: "0.3.3"

source:
  git_url: https://github.com/soft-matter/pims
  git_tag: v0.3.3

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - slicerator >=0.9.4
    - six >=1.8
    - numpy >=1.7

  run:
    - python
    - slicerator >=0.9.4
    - six >=1.8
    - numpy >=1.7
    - scikit-image  # one of { scikit-image | matplotlib | scipy }
    - pillow <3 # optional, but necessary for ipython rich display

test:
  imports:
    - pims
    - pims.api
    - pims.base_frames
    - pims.bioformats
    - pims.cine
    - pims.display
    - pims.ffmpeg_reader
    - pims.frame
    - pims.image_sequence
    - pims.norpix_reader
    - pims.pyav_reader
    - pims.spe_stack
    - pims.tiff_stack
    - pims.tests
    - pims.utils
    - pims.utils.misc
    - pims.utils.sort

about:
  home: https://github.com/soft-matter/pims
  license: BSD
  summary: 'Python Image Sequence'
