{% set version = "1.1.0" %}

package:
    name: mongoquery
    version: {{ version }}

source:
    fn: mongoquery-{{ version }}.tar.gz
    url: https://github.com/kapouille/mongoquery/archive/v{{ version }}.tar.gz
    sha256: d1e87f6038ea074273610b6258e5af7477de61c782f6424fc7ecf3416df3e645

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    skip: True  # [py2k]

requirements:
    build:
        - python
        - setuptools

    run:
        - python

test:
    imports:
        - mongoquery
    requires:
        - nose
    commands:
        - nosetests {{ environ.SRC_DIR }}/tests -sv

about:
    home: http://github.com/kapouille/mongoquery
    license: The Unlicense
    summary: >
        A utility library that provides a MongoDB-like query language for 
        querying python collections. It's mainly intended to parse objects 
        structured as fundamental types in a similar fashion to what is 
        produced by JSON or YAML parsers.

extra:
    recipe-maintainers:
        - ericdill
        - licode
        - tacaswell
