{% set version = "v0.9.1" %}
package:
  name: xattr
  version: {{ version }}

source:
  git_url: https://github.com/xattr/xattr.git
  git_rev: {{ version }}

build:
  number: 1
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - cffi >=1.0
  run:
    - python
    - cffi >=1.0

test:
  imports:
    - xattr
