package:
  name: super_state_machine
  version: 1.0

source:
  git_url: https://github.com/beregond/super_state_machine
  git_rev: 1.0
  patches:
    - nuke_enum34.patch [py3k]

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - enum34 [py2k]
    - six

  run:
    - python
    - enum34  [py2k]
    - six

test:
  imports:
    - super_state_machine

about:
  home: https://github.com/beregond/super_state_machine
  license: BSD License
  summary: 'Super State Machine gives you utilities to build finite state machines.'

