package:
  name: metadatastore
  version: 0.5.0

source:
  git_url: https://github.com/NSLS-II/metadatastore
  git_rev: v0.5.0
  patches:
    - config.patch

build:
  number: 0

requirements:
  build:
    - python
    - six

  run:
    - boltons
    - doct
    - numpy
    - pymongo
    - python
    - pytz
    - pyyaml
    - six

test:
  requires:
    - nslsii_dev_configuration

  imports:
    - metadatastore

about:
  home: https://github.com/NSLS-II/metadatastore
  license: BSD
