package:
  name: datamuxer
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'GIT_STUB')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 'GIT_STUB')   }}

source:
  git_url: https://github.com/NSLS-II/datamuxer
  git_rev: master

build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}_py{{ py }}

requirements:
  build:
    - python

  run:
    - python
    - pandas
    - six
    - scipy
    - tzlocal

test:
  requires:
    - nslsii_dev_configuration
    - databroker
  imports:
    - datamuxer

about:
  home: https://github.com/NSLS-II/datamuxer
  license: BSD
