{% set name = "modestimage" %}
{% set version = "v0.1.post28+hg91e2c1d" %}
{% set file_ext = "tar.gz" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: https://github.com/ChrisBeaumont/mpl-modest-image
  git_rev: 91e2c1d0c020f5e5de9ce1fe767f4f1df1c627a8

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - matplotlib
    - numpy

test:
  imports:
    - modest_image

about:
  home: The package home page
  license: MIT License
  license_family: MIT
  summary: Friendlier matplotlib interaction with large images

extra:
  recipe-maintainers:
    - mrakitin
