{% set version = "0.8.0" %}
package:
  name: filestore
  version: {{ version }}

source:
  git_url: https://github.com/nsls-ii/filestore
  git_rev: v{{ version }}
  patches:
    - config.patch

build:
  number: 0
  script: |
    sed -i 's|__CONDA_BUILD_PLACEHOLDER__|'$PREFIX'/etc|' filestore/conf.py && \
    python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python
    - setuptools

  run:
    - boltons
    - doct
    - h5py
    - jsonschema
    - numpy
    - pims
    - pymongo
    - python
    - pyyaml
    - six
    - tifffile

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - filestore

about:
  home: https://github.com/NSLS-II/filestore
  license: BSD
