{% set version = "0.5.0" %}
package:
  name: filestore
  version: {{ version }}

source:
  url: https://github.com/NSLS-II/filestore/archive/v{{ version }}.tar.gz
  fn: filestore-v{{ version }}.tar.gz
  sha256: 74125a5df5fd07663ad9e5084f62bd85d01a65f87fb621103696a77a45fb48f5
  patches:
    - config.patch
build:
  number: 0
  script: |
    sed -i 's|__CONDA_BUILD_PLACEHOLDER__|'$PREFIX'/etc|' filestore/conf.py && \
    python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python
    - setuptools

  run:
    - doct
    - h5py
    - jsonschema
    - numpy
    - pims
    - pymongo
    - python
    - pyyaml
    - six
    - tifffile

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - filestore

about:
  home: https://github.com/NSLS-II/filestore
  license: BSD
