{% set version = "0.6.0" %}

package:
  name: metadatastore
  version: {{ version }}

source:
  git_url: https://github.com/NSLS-II/metadatastore
  git_rev: v{{ version }}
  patches:
    - config.patch

build:
  number: 0

requirements:
  build:
    - python
    - six

  run:
    - boltons
    - doct
    - numpy
    - pymongo >=3.2
    - python
    - pytz
    - pyyaml
    - six

test:
  requires:
    - nslsii_dev_configuration

  imports:
    - metadatastore

about:
  home: https://github.com/NSLS-II/metadatastore
  license: BSD
