{% set version = "0.6.0" %}

package:
  name: metadatastore
  version: {{ version }}

source:
  url: https://github.com/NSLS-II/metadatastore/archive/v{{ version}}.tar.gz
  fn: metadatastore-v{{ version }}.tar.gz
  patches:
    - config.patch

build:
  number: 0

requirements:
  build:
    - python
    - six

  run:
    - boltons
    - doct
    - numpy
    - pymongo
    - python
    - pytz
    - pyyaml
    - six

test:
  requires:
    - nslsii_dev_configuration

  imports:
    - metadatastore

about:
  home: https://github.com/NSLS-II/metadatastore
  license: BSD
