{% set year = "2018" %}
{% set cycle = "1" %}
{% set version ="0" %}

package:
  name: 07-bm-qas-collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - isstools
    - netcdf4
