{% set year = "2018" %}
{% set cycle = "2" %}
{% set version ="0" %}

package:
  name: 07-bm-qas-collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 2

requirements:
  run:
    - isstools
    - lightflow
    - kafka-python
