{% set year = "2019" %}
{% set cycle = "2" %}
{% set version ="0" %}

package:
  name: 07-bm-qas-collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - qastools
    - xraylarch
