package:
  name: pyxrf
  version: {{ environ.GIT_DESCRIBE_TAG }}.post{{ environ.GIT_DESCRIBE_NUMBER }}

source:
  git_url: https://github.com/NSLS-II/pyxrf
  git_rev: master

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - pyxrf = pyxrf.gui:run
  skip: True  # [py3k]

requirements:
  build:
    - python
    - numpy
    - enaml
    - setuptools

  run:
    - python
    - enaml
    - h5py
    - matplotlib
    - numpy
    - pandas
    - scikit-beam

test:
  imports:
    - pyxrf

about:
  home: https://github.com/NSLS-II/pyxrf
  license: 3-Clause BSD

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
