{% set year = "2018" %}
{% set cycle = "2" %}
{% set version ="0" %}

package:
  name: 23-id-1-csx1-analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 1

requirements:
  run:
    - csxtools
