{% set year = "17" %}
{% set cycle = "Q1" %}
{% set version ="0" %}

package:
  name: 23-id-1-csx1-analysis
  version: {{ year }}{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - csxtools
