package:
  name: historydict
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/Nikea/historydict.git
  git_rev: master

build:
  number: 1

requirements:
  build:
    - python

  run:
    - python
    - six

test:
  imports:
    - historydict
