package:
  name: chxtools
  version: 0.0.2

source:
  git_url: https://github.com/NSLS-II-CHX/chxtools
  git_rev: v0.0.2

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - matplotlib
    - numpy
    - pims >0.2.2
    - h5py
    - hdf5-lz4
    - prettytable
    - fabio

test:
  imports:
    - 'chxtools'
    - 'chxtools.pims_readers'

about:
  home: https://github.com/NSLS-II/dataportal
  license: BSD
