package:
  name: bluesky
  version: 0.5.1

source:
  git_url: https://github.com/NSLS-II/bluesky
  git_rev: v0.5.1

build:
  # Note that this will override the default build string with the Python
  # and NumPy versions
  number: 0

requirements:
  build:
    - python

  run:
    - boltons
    - cycler
    - databroker
    - doct
    - event-model
    - filestore
    - historydict
    - jinja2
    - jsonschema
    - metadatastore
    - matplotlib
    - numpy
    - python
    - scipy
    - super_state_machine
    - tifffile
    - traitlets
    - xray-vision
#    - IPython

test:
  requires:
    - nslsii_dev_configuration
    - databroker
#    - ophyd
    - pyepics
  imports:
    - bluesky

about:
  home: https://github.com/NSLS-II/bluesky
  license: BSD
