package:
  name: album
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'GIT_TAG_PLACEHOLDER')[1:]  }}.post{{ environ.get('GIT_DESCRIBE_NUMBER') }}

source:
  git_url: https://github.com/NSLS-II/album
  git_rev: master

build:
  number: 1
  entry_points:
    - album = album.server:run

requirements:
  build:
    - python
    - numpy
    - setuptools

  run:
    - python
    - bokeh
    - flask
    - databroker >=v0.3.0
    - numpy

test:
  imports:
    - album
