{% set version = "0.9.37" %}

package:
    name: xraylarch
    version: {{ version }}

source:
    git_url: https://github.com/xraypy/xraylarch
    git_rev: {{ version }}

build:
    number: 1
    script: python setup.py install --single-version-externally-managed --record=record.txt
    skip: True  # [py2k]

requirements:
    build:
        - python

    run:
        - six>=1.10
        - scipy>=0.17
        - numpy>=1.7
        - matplotlib>=1.5.1
        - sqlalchemy>=0.9
        - h5py>=2.2
        - pillow>=3.4
        - peakutils>=1.0.0
        - requests>=2.1
        - asteval>=0.9.12
        - lmfit>=0.9.9
        - psutil


about:
    home: https://github.com/xraypy/xraylarch
