package:
  name: ixstools
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'GGIT_STUB')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 'GIT_STUB') }}

source:
  git_url: https://github.com/NSLS-II-IXS/ixstools
  git_rev: master

build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}
  entry_points:
    - align = ixstools.align:main

requirements:
  build:
    - python
  run:
    - python
    - lmfit
    - matplotlib
    - numpy
    - pandas
    - scipy
    - pyyaml

test:
  requires:
    - nose
    - coverage
  imports:
    - ixstools
    - ixstools.align
    - ixstools.fit
    - ixstools.io

about:
  home: http://scikit-beam.github.io/scikit-beam/
  license: 3-Clause BSD
