package:
    name: metadataclient
    version: {{ environ.GIT_DESCRIBE_TAG[1:] }}.post{{ environ.GIT_DESCRIBE_NUMBER }}

source:
    git_url: https://github.com/nsls-ii/metadataclient
    git_rev: master

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    skip: True   # [py2k]

requirements:
    build:
        - python
        - setuptools

    run:
        - doct
        - python
        - requests
        - ujson
        - pyyaml
test:
    imports:
        - metadataclient
        - metadataclient.tests

about:
    home: https://nsls-ii.github.io/metadataclient
    license: BSD 3-Clause
    summary: "metadataservice is the server for metadataclient built on top of mds"

extra:
    recipe-maintainers:
        - arkilic
        - tacaswell
        - licode
