package:
    name: lmfit
    version: 0.8.3

source:
    git_url: http://github.com/lmfit/lmfit-py.git
    git_tag : 0.8.3

build:
    number: 0

requirements:
    build:
        - python
        - numpy
        - scipy

    run:
        - python
        - numpy
        - scipy
        - matplotlib
        - ipython
        - pandas

test:
    imports:
        - lmfit

about:
    home: http://lmfit.github.io/lmfit-py/
    license: BSD
