package:
  name: xray-vision
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'GIT_TAG_PLACEHOLDER')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER') }}

source:
  git_url: https://github.com/Nikea/xray-vision
  git_rev: master

build:
  number: 1

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - matplotlib
    - pyqt
    - six

test:
  requires:
    - nose

  imports:
    - xray_vision
    - xray_vision.qt_widgets
    - xray_vision.messenger
    - xray_vision.messenger.mpl
    - xray_vision.backend
    - xray_vision.backend.mpl


about:
  home: https://github.com/Nikea/xray-vision
  license: 3-Clause BSD
