{% set version = "2.4.2" %}

package:
  name: libtool
  version: {{ version }}

source:
  fn: libtool-{{ version }}.tar.gz
  url: http://ftpmirror.gnu.org/libtool/libtool-{{ version }}.tar.gz
  sha256: b38de44862a987293cd3d8dfae1c409d514b6c4e794ebc93648febf9afc38918

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - automake
    - autoconf

test:
  commands:
    - libtool --help

about:
  home: http://www.gnu.org/software/libtool/
  license: GPL 3
