{% set version = "0.0.6" %}

package:
  name: pyxrf
  version: {{ version }}

source:
  git_url: https://github.com/nsls-ii/pyxrf
  git_rev: v{{ version }}

build:
  number: 1
  entry_points:
    - pyxrf = pyxrf.gui:run
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - atom
    - enaml
    - h5py
    - ipython-notebook
    - ipywidgets
    - lmfit
    - matplotlib
    - numpy
    - pandas
    - pillow
    - python
    - scipy
    - six
    - scikit-beam
    - scikit-image

about:
  home: https://github.com/NSLS-II/pyxrf
  license: 3-Clause BSD
