{% set version = "0.0.5" %}

package:
  name: pyxrf
  version: {{ version }}

source:
  url: https://github.com/NSLS-II/pyxrf/archive/v{{ version }}.tar.gz
  fn: pyxrf-v{{ version }}.tar.gz
  sha256: 50f8adbd9ae8c81e4419a208bfb2718f9f9aba467785c3679cbef3c58e25fde2

build:
  number: 1
  entry_points:
    - pyxrf = pyxrf.gui:run
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [not py2k]

requirements:
  build:
    - python
    - setuptools

  run:
    - atom
    - enaml
    - h5py
    - lmfit
    - matplotlib
    - numpy
    - pandas
    - pillow
    - python
    - scipy
    - six
    - scikit-beam
    - scikit-image

about:
  home: https://github.com/NSLS-II/pyxrf
  license: 3-Clause BSD
