# Full credit goes to https://github.com/conda/conda-recipes for providing this recipe.
# It has been subsequently adapted for automated building with conda-forge.
package:
  name: matplotlib
  version: {{ environ.get('GIT_DESRIBE_TAG', 'GIT_STUB')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 'GIT_STUB') }}

source:
  git_url: https://github.com/tacaswell/matplotlib
  git_rev: 513da025fea352bdbdec802cd4fa459fac213142
  patches:
    # A patch to add Tcl directly to the search path on Windows.
    - setupext.patch      # [win]
    # A patch to make Qt4Agg the default backend.
    - cfg_qt4agg.patch    # [linux]
    # Patches the matplotlibrc template to default to Qt4.
    - rctmp_pyside.patch  # [not osx]
    # Patches setupext to look in PREFIX for the tcl/tk headers.
    - osx-tk.patch        # [osx]

build:
  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', 'GIT_STUB')_BUILD_STR'] }}_py{{ py }}


# On Windows, the following error occurs for x64:
# src/ft2font.cpp(5) : fatal error C1083: Cannot open include file: 'string': No such file or directory
build:  # [win64]
    skip:  # [win64]
        - True  # [win64]

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - python-dateutil
    - freetype
    - msinttypes          # [win]
    - cycler
    - nose
    - pyparsing
    - pytz
#    - py2cairo            # [linux and py2k]
    - tornado
    - libpng
    - zlib                # [win]
    - pyqt                # [not osx]
    - tk                  # [linux]
  run:
    - python
    - numpy x.x
    - cycler
    - python-dateutil
    - freetype
    - pytz
    - pyparsing
#    - py2cairo            # [linux and py2k]
    - libpng              # [unix]
    - pyqt                # [not osx]
    - tk                  # [linux]

test:
    imports:
        - matplotlib
        - matplotlib.pyplot

about:
  home: http://matplotlib.org/
  license: PSF-based (http://matplotlib.org/users/license.html)
  summary: Publication quality figures in Python

extra:
  recipe-maintainers:
    - pelson
    - tacaswell
    - JanSchulz
