{% set version = "1.16" %}
package:
  name: gsl
  version: {{ version }}

source:
  fn: gsl-{{ version }}.tar.gz
  url: http://ftp.club.cc.cmu.edu/pub/gnu/gsl/gsl-{{ version }}.tar.gz
  sha256: 73bc2f51b90d2a780e6d266d43e487b3dbd78945dd0b04b14ca5980fe28d2f53

build:
  number: 3
  skip: True  # [not linux]


about:
  home: http://www.gnu.org/software/gsl/
  license: GPL 3
