package:
  name: csxtools
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: https://github.com/NSLS-II-CSX/csxtools
  git_rev: master

build:
  number: 0
  string: {{ environ['GIT_BUILD_STR'] }}_np{{ np }}_py{{ py }}

requirements:
  build:
    - setuptools
    - python
    - numpy x.x
    - pytest

  run:
    - python
    - numpy x.x
    - matplotlib
    - tzlocal
    - ipython
    - ipywidgets
    - databroker
    - pims >=0.3.2

test:
  requires:
    - pytest
    - nslsii_dev_configuration
  imports:
    - csxtools
    - csxtools.ext
    - csxtools.ext.fastccd
    - csxtools.ext.image
    - csxtools.ext.phocount

about:
  home: https://github.com/NSLS-II-CSX/csxtools
  license: BSD 3-clause
