# Copyright 2014-2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.
{% set version = "2.45.8" %}
package:
  name: glib
  version: {{ version }}

source:
  fn: glib-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/glib/2.45/glib-{{ version }}.tar.xz
  md5: a14af72f3ded4940b2397832b68a75b4

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: True  # [not linux]

requirements:
  build:
    - libffi
    - python
    - zlib
    - gettext
  run:
    - libffi
    - zlib
    - gettext

about:
  home: http://www.gtk.org/
  license: LGPL
  summary: a low-level portability and utility library
