package:
  name: tifffile
  version: 0.7.0

source:
  git_rev: v0.7.0
  git_url: https://github.com/blink1073/tifffile

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy x.x

  run:
    - python
    - numpy x.x

test:
  imports:
    - tifffile

about:
  home: http://github.com/blink1073/tifffile
  license:  BSD License
  summary: 'Read and write image data from and to TIFF files.'
