package:
  name: suitcase
  version: 0.2.2

source:
  git_url: https://github.com/NSLS-II/suitcase.git
  git_rev: v0.2.2

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - databroker
    - h5py

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - suitcase
