package:
  name: keyring
  version: "5.3"

source:
  git_rev: 5.3
  git_url: https://github.com/jaraco/keyring

build:
  entry_points:
    - keyring=keyring.cli:main
  number: 0

requirements:
  build:
    - python
    - setuptools
    - hgtools

  run:
    - python

test:
  imports:
    - keyring
    - keyring.backends
    - keyring.tests
    - keyring.tests.backends
    - keyring.util

  commands:
    - keyring --help

about:
  home: http://github.com/jaraco/keyring
  license: Python Software Foundation License or MIT License
  summary: 'Store and access your passwords safely.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
