package:
  name: eiger-io
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/NSLS-II-CHX/eiger-io.git
  git_rev: master

build:
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - h5py
    - numpy
    - filestore
    - pims

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - eiger_io.fs_handler
    - eiger_io.pims_reader

about:
  home: https://github.com/CHX-NSLS-II/eiger-io
  license: BSD
