package:
  name: metadatastore
  version: {{ environ.GIT_DESCRIBE_TAG[1:] }}.post{{ environ.GIT_DESCRIBE_NUMBER }}

source:
  git_url: https://github.com/NSLS-II/metadatastore.git
  git_rev: master
  patches:
    - config.patch

build:
  number: 0

requirements:
  build:
    - python
    - six
  run:
    - python
    - pymongo
    - six
    - pyyaml
    - prettytable
    - humanize
    - numpy
    - pytz
    - jinja2
    - doct

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - metadatastore
    - metadatastore.conf
    - metadatastore.examples
    - metadatastore.examples.sample_data
    - metadatastore.examples.sample_data.common
    - metadatastore.examples.sample_data.multisource_event
    - metadatastore.examples.sample_data.temperature_ramp

about:
  home: https://github.com/NSLS-II/metadatastore
  license: BSD

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
