{% set version = "2.0.1" %}

package:
  name: chxtools
  version: {{ version }}

source:
  url: https://github.com/NSLS-II-CHX/chxtools/archive/v{{ version }}.tar.gz
  fn: chxtools-v{{ version }}.tar.gz

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - atom
    - cython
    - databroker
    - enaml
    - fabio
    - h5py
    - hdf5-lz4
    - python
    - matplotlib
    - eiger-io
    - numpy
    - pandas
    - prettytable
    - pyepics
    - pymongo
    - scikit-beam
    - scikit-image
    - scipy

test:
  imports:
    - chxtools

about:
  home: https://github.com/NSLS-II-CHX/chxtools
  license: BSD
