package:
  name: databroker
  version: 0.3.1

source:
  git_url: http://github.com/NSLS-II/databroker
  git_rev: v0.3.1

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python
    - pandas
    - pims
    - metadatastore >=v0.2.0
    - filestore >=v0.2.0
    - channelarchiver
    - six
    - tzlocal
    - singledispatch [py27]
    - doct

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - databroker
    - databroker.testing
    - databroker.examples
    - databroker.examples.sample_data
    - databroker.utils

about:
  home: http://github.com/NSLS-II/databroker
  license: BSD
