{% set version = "0.2.0.dev" %}

package:
  name: kiwisolver
  version: {{ version }}

source:
  git_url: https://github.com/MatthieuDartiailh/kiwi
  git_rev: {{ version }}

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - kiwisolver

about:
  home: https://github.com/nucleic/kiwi
  license: Modified BSD
  summary: 'A fast implementation of the Cassowary constraint solver'
