{% set version = "1.47.1" %}

package:
  name: gobject-introspection
  version: {{ version }}

source:
  fn: gobject-introspection-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/gobject-introspection/1.47/gobject-introspection-{{ version }}.tar.xz
  md5: 8548fed2f999902accbf45cafe5a078c
  patches:
    - ffi-config.patch

build:
  number: 3
  detect_binary_files_with_prefix: true
  skip: True  # [py2k]

requirements:
  build:
    - cairo-gobject
    - glib
    - libffi
    - python
  run:
    - python
    - glib
    - libffi

about:
  home: http://wiki.gnome.org/action/show/Projects/GObjectIntrospection
  license: LGPL
