{% set version = "0.2.0" %}

package:
    name: metadataservice 
    version: {{ version }}

source:
    git_url: https://github.com/nsls-ii/metadataservice
    git_rev: v{{ version }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    skip: True   # [py2k]

requirements:
    build:
        - python
        - setuptools

    run:
        - doct
        - jsonschema
        - pymongo
        - python
        - requests
        - tornado
        - ujson
        - pyyaml
test:
    imports:
        - metadataservice
        - metadataservice.test
        - metadataservice.server

about:
    home: https://nsls-ii.github.io/metadataservice
    license: BSD 3-Clause
    summary: "metadataservice is the server for metadataclient built on top of mds"

extra:
    recipe-maintainers:
        - arkilic
        - tacaswell
        - licode
