package:
  name: event-model
  version: {{ environ.GIT_DESCRIBE_TAG }}.post{{ environ.GIT_DESCRIBE_NUMBER }}

source:
  git_url: https://github.com/NSLS-II/event-model
  git_rev: master

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - event_model

about:
  home: https://github.com/NSLS-II/event_model
  license: BSD
