{% set version = "0.1.5" %}

package:
    name: pyzbar
    version: {{ version }}

source:
    git_url: https://github.com/NaturalHistoryMuseum/pyzbar
    git_rev: v{{ version }}

build:
    number: 0
    skip: True  # [win]

requirements:
    build:
        - python
    run:
        - python
        - coveralls >=1.1
        - nose >=1.3.4
        - numpy >=1.8.2
        - pillow >=3.2.0

test:
    imports:
        - pyzbar.pyzbar
        - PIL

about:
    home: https://github.com/NaturalHistoryMuseum/pyzbar
    license: MIT
    summary: Read one-dimensional barcodes and QR codes using the zbar library

extra:
    recipe-maintainers:
        - mrakitin
