{% set version = "0.1.5" %}

package:
    name: pyzbar
    version: {{ version }}

source:
    git_url: https://github.com/NaturalHistoryMuseum/pyzbar
    git_rev: v{{ version }}

build:
    number: 0
    skip: True  # [win]

requirements:
    build:
        - python
        - libzbar0
    run:
        - python
        - coveralls>=1.1
        - nose>=1.3.4
        - numpy>=1.8.2
        - Pillow>=3.2.0

test:
    imports:
        - pyzbar
        - PIL

about:
    home: https://github.com/NaturalHistoryMuseum/pyzbar
    license: MIT
    summary: Read one-dimensional barcodes and QR codes using the zbar library

extra:
    recipe-maintainers:
        - mrakitin
