package:
  name: bluesky
  version: 0.4.1

source:
  git_url: https://github.com/NSLS-II/bluesky
  git_rev: v0.4.1

build:
  # Note that this will override the default build string with the Python
  # and NumPy versions
  number: 1

requirements:
  build:
    - python

  run:
    - python
    - jsonschema
    - super_state_machine
    - numpy
    - metadatastore
    - filestore
    - matplotlib
    - prettytable
    - cycler
    - traitlets
    - historydict
    - lmfit

test:
  requires:
    - nslsii_dev_configuration
    - databroker
    - xray-vision
    - tifffile
    - pyepics
  imports:
    - bluesky
    - bluesky.broker_callbacks
    - bluesky.broker_examples
    - bluesky.examples
    - bluesky.global_state
    - bluesky.hardware_checklist
    - bluesky.plans
    - bluesky.qt_kicker
    - bluesky.register_mds
    - bluesky.run_engine
    - bluesky.scientific_callbacks
    - bluesky.simple_scans
    - bluesky.spec_api
    - bluesky.standard_config
    - bluesky.suspenders  # requires pyepics
    - bluesky.utils
    - bluesky.callbacks
    - bluesky.callbacks.core
    - bluesky.callbacks.olog

about:
  home: https://github.com/NSLS-II/bluesky
  license: BSD
