package:
  name: doct
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'GIT_TAG_PLACEHOLDER')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER') }}

source:
  git_url: https://github.com/NSLS-II/doct
  git_rev: master

build:
  number: 2

requirements:
  build:
    - python
    - six

  run:
    - python
    - six
    - humanize
    - prettytable

test:
  imports:
    # Import all the packages
    - doct

about:
  home: https://github.com/NSLS-II/document
  license: BSD
