package:
  name: csxtools
  version: 0.1.2

source:
  git_url: https://github.com/NSLS-II-CSX/csxtools
  git_rev: v0.1.2

build:
  number: 0

requirements:
  build:
    - setuptools
    - python
    - numpy x.x
    - pytest

  run:
    - python
    - numpy x.x
    - matplotlib
    - tzlocal
    - ipython
    - ipywidgets
    - databroker

test:
  requires:
    - pytest
  imports:
    - csxtools
    - csxtools.ext
    - csxtools.ext.fastccd
    - csxtools.ext.image
    - csxtools.ext.phocount

about:
  home: https://github.com/NSLS-II-CSX/csxtools
  license: BSD 3-clause
