{% set version = "0.3" %}

package:
  name: recordwhat
  version: {{ version }}

source:
  url: https://github.com/klauer/recordwhat/archive/{{ version }}.tar.gz
  fn: recordwhat-{{ version }}.tar.gz

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - six
  run:
    - numpy
    - ophyd
    - pandas
    - pyepics

test:
  imports:
    - recordwhat

about:
  home: https://github.com/klauer/recordwhat
  license: BSD
