package:
  name: slicerator
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'GGIT_STUB')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 'GIT_STUB') }}

source:
  git_url: https://github.com/soft-matter/slicerator.git
  git_rev: master

build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}_py{{ py }}

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - six
test:
  imports:
    - slicerator

about:
  home: http://github.com/soft-matter/slicerator
  license: BSD
  summary: 'A lazy-loading, fancy-sliceable iterable.'
