package:
  name: pyasn1-modules
  version: 0.0.5

source:
  git_url: https://github.com/coruus/pyasn1-modules
  git_rev: release_0_0_5_tag

build:
  number: 1

requirements:
  build:
    - python
    - pyasn1 >=0.1.4

  run:
    - python
    - pyasn1 >=0.1.4

test:
  imports:
    - pyasn1_modules

about:
  home: http://sourceforge.net/projects/pyasn1/
  license: BSD License
  summary: 'A collection of ASN.1-based protocols modules.'
