package:
  name: album
  version: 0.0.1


source:
  git_url: https://github.com/NSLS-II/album
  git_rev: v0.0.1

build:
  number: 0
  string: {{ environ['CONDA_BUILD'] }}_py{{ py }}
  entry_points:
    - album = album.server:run

requirements:
  build:
    - python
    - numpy
    - setuptools

  run:
    - python
    - bokeh
    - flask
    - dataportal >=0.2.0
    - numpy

test:
  imports:
    - album
