{% set version = "2.0.2" %}

package:
    name: pychx
    version: {{ version }}

source:
    git_url: https://github.com/NSLS-II-CHX/pyCHX
    git_rev: v{{ version }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    skip: True  # [py2k]

requirements:
    build:
        - python

    run:
        - chxtools
        - databroker
        - h5py
        - matplotlib
        - numpy
        - pandas
        - pillow
        - pyolog
        - python
        - reportlab
        - scikit-image
        - scipy
        - scikit-beam
        - tqdm
        - xray-vision

test:
    imports:
        - pyCHX

about:
    home: https://github.com/NSLS-II-CHX/pyCHX
    license: BSD


