package:
  name: hgtools
  version: 6.3

source:
  git_rev: 6.3
  git_url: https://github.com/jaraco/hgtools

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - hgtools
    - hgtools.managers
    - hgtools.tests

about:
  home: https://github.com/jaraco/hgtools/
  license: GNU General Public License (GPL)
  summary: 'Classes and setuptools plugin for Mercurial repositories'
