package:
  name: databroker
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'GIT_STUB')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 'GIT_STUB') }}

source:
  git_url: https://github.com/NSLS-II/databroker
  git_rev: master

build:
  # Note that this will override the default build string with the Python version
  string: {{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}_py{{ py }}
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - pandas
    - pims
    - metadatastore >=v0.2.0
    - filestore >=v0.2.0
    - channelarchiver
    - six
    - tzlocal
    - singledispatch [py27]

test:
  requires:
    - nslsii_dev_configuration
    - filestore
  imports:
    - databroker
    - databroker.testing
    - databroker.examples
    - databroker.examples.sample_data
    - databroker.utils

about:
  home: https://github.com/NSLS-II/databroker
  license: BSD
