{% set version = "0.9.3" %}

package:
  name: lmfit
  version: {{ version }}

source:
  git_url: https://github.com/lmfit/lmfit-py
  git_rev: {{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - numpy
    - scipy

  run:
#    - emcee
    - ipython
    - ipywidgets
    - matplotlib
    - numpy
    - pandas
    - python
    - scipy

test:
  requires:
    - nose
  commands:
    - nosetests -sv {{ environ.SRC_DIR }}
  imports:
    - lmfit

about:
  home: http://lmfit.github.io/lmfit-py/
  license: BSD
  summary: >
      Non-Linear Least Squares Minimization, with flexible Parameter
      settings, based on scipy.optimize.leastsq, and with many additional
      classes and methods for curve fitting http:/lmfit.github.io/lmfit-py/

extra:
  recipe-maintainers:
    - ericdill
    - tacaswell
    - licode

