package:
  name: mongoengine
  version: 0.8.7

source:
  git_rev: v0.8.7
  git_url: http://github.com/MongoEngine/mongoengine/archive/v0.8.7.tar.gz

build:
  number: 2

requirements:
  build:
    - python
    - setuptools
    - pymongo ==2.8

  run:
    - python
    - pymongo ==2.8

test:
  imports:
    - bson
    - mongoengine
    - mongoengine.base
    - mongoengine.django
    - mongoengine.django.mongo_auth
    - mongoengine.queryset

about:
  home: http://mongoengine.org/
  license: MIT License
  summary: 'MongoEngine is a Python Object-Document Mapper for working with MongoDB.'
