{% set year = "2018" %}
{% set cycle = "2" %}
{% set version ="0" %}

package:
  name: 12-id-smi-collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 4

requirements:
  run:
    - peakutils
