{% set year = "2019" %}
{% set cycle = "1" %}
{% set version ="0" %}

package:
  name: 11-id-chx-analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - boto3
    - chxtools
    - dask
    - eiger-io
    - graphviz
    - hdf5-lz4
    - line_profiler
    - pyCHX
    - pyolog
    - pytables
    - reportlab
    - theano
