{% set year = "17" %}
{% set cycle = "Q1" %}
{% set version ="0" %}

package:
  name: 08-id-iss-analysis
  version: {{ year }}{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - isstools
    - netcdf4
