{% set version = "0.0.2" %}

package:
  name: chxtools
  version: {{ version }}

source:
  url: https://github.com/NSLS-II-CHX/chxtools/archive/v{{ version }}.tar.gz
  fn: chxtools-v{{ version }}.tar.gz
  sha256: 504bf0f92ae7d83d3ba5e38a718b67ccdae5887c9d28e8a0bf169754745bd45c

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - fabio
    - h5py
    - hdf5-lz4
    - python
    - matplotlib
    - numpy
    - pims >0.2.2
    - prettytable

test:
  imports:
    - chxtools
    - chxtools.pims_readers

about:
  home: https://github.com/NSLS-II/dataportal
  license: BSD
