package:
  name: metadatastore
  version: {{ environ['GIT_DESCRIBE_TAG'][1:] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: https://github.com/NSLS-II/metadatastore.git
  git_rev: master
  patches:
    - config.patch
  # use a local url and leave rev blank to have conda build current head, currently
  # requires master branch of conda-build to work
  # git_rev: ?

build:
  string: {{ environ['GIT_BUILD_STR'] }}_py{{ py }}
  number: 0

requirements:
  build:
    - python
    - six
  run:
    - python
    - pymongo
    - six
    - pyyaml
    - prettytable
    - humanize
    - numpy
    - pytz
    - jinja2
    - boltons
    - doct

test:
  requires:
    - nslsii_dev_configuration
  # Python imports
  imports:
    - metadatastore
    - metadatastore.commands
    - metadatastore.api
    - metadatastore.conf
    - metadatastore.utils

about:
  home: https://github.com/NSLS-II/metadatastore
  license: BSD
