package:
  name: metadatastore
version: {{ GIT_DESCRIBE_TAG }}.post{{ GIT_DESCRIBE_NUMBER }}

source:
  git_url: https://github.com/NSLS-II/metadatastore.git
  git_rev: master
  patches:
    - config.patch

build:
  number: 1

requirements:
  build:
    - python
    - six
  run:
    - python
    - pymongo
    - six
    - pyyaml
    - prettytable
    - humanize
    - numpy
    - pytz
    - jinja2
    - boltons
    - doct

test:
  requires:
    - nslsii_dev_configuration
  # Python imports
  imports:
    - metadatastore

about:
  home: https://github.com/NSLS-II/metadatastore
  license: BSD
