{% set version = "17Q1.0" %}

package:
  name: collection
  version: {{ version }}

requirements:
  run:
    - analysis ==17Q1.0
    - ophyd ==0.4.0
    - pyepics ==3.2.6
    - pyolog ==4.1.0
    - pyqt ==4.11
