{% set version = "5.9" %}

package:
  name: ncurses
  version: {{ version }}

source:
  fn: ncurses-{{ version }}.tar.gz
  url: http://ftp.gnu.org/pub/gnu/ncurses/ncurses-{{ version }}.tar.gz
  md5: 8cb9c412e5f2d96bc6f459aa8c6282a1

build:
  number: 8
  detect_binary_files_with_prefix: true

about:
  home: http://www.gnu.org/software/ncurses/
  license:  Free software (X11 License)
