package:
  name: pymongo
  version: 3.2.2

source:
  git_url: https://github.com/mongodb/mongo-python-driver
  git_rev: 3.2.2

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - bson
    - gridfs
    - pymongo

about:
  home: https://github.com/mongodb/mongo-python-driver
  license: Apache Software License
  summary: 'Python driver for MongoDB <http://www.mongodb.org>'
