{% set version = "0.0.8" %}
package:
  name: xray-vision
  version: {{ version }}

source:
  url: https://github.com/Nikea/xray-vision/archive/v{{ version }}.tar.gz
  fn: xray-vision-v{{ version }}.tar.gz

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
  run:
    # icu is needed until https://github.com/conda-forge/staged-recipes/issues/907 is resolved
    - icu  # [py34]
    - python
    - matplotlib
    - numpy
    - pandas
    - pyqt
    - scipy
    - six

test:
  imports:
    - xray_vision
    - xray_vision.backend
    - xray_vision.backend.mpl
    - xray_vision.mask
    - xray_vision.messenger
    - xray_vision.messenger.mpl
    - xray_vision.mpl_plotting
    - xray_vision.qt_widgets
    - xray_vision.utils

about:
  home: https://github.com/Nikea/xray-vision
  license: BSD 3-Clause
  summary: Visualization widgets and plotting helpers targeted at X-Ray Sciences

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
