{% set name = "ipyvolume" %}
{% set version = "0.4.2" %}
{% set sha256 = "738738d104899c046913041c3f92aa3ac274f4127bd8e052120be21f32f4eddd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - traittypes
    - traitlets
    - ipywidgets >=7.0
    - pillow
    - scipy
    - numpy
    - scikit-image >=0.13
    - requests
    - ipywebrtc

test:
  imports:
    - ipyvolume

about:
  home: https://github.com/maartenbreddels/ipyvolume
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'IPython widget for rendering 3d volumes in the Jupter notebook'
  doc_url: https://ipyvolume.readthedocs.io/
  dev_url: https://github.com/maartenbreddels/ipyvolume

extra:
  recipe-maintainers:
    - maartenbreddels
