
{% set version = "0.9.0" %}

package:
  name: databroker
  version: {{ version }}

source:
  git_url: https://github.com/nsls-II/databroker
  git_rev: v{{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - attrs >=16.3.0
    - boltons
    - doct
    - h5py
    - numpy
    - pandas
    - pims
    - pymongo
    - python
    - pytz
    - requests
    - singledispatch [py27]
    - six
    - tifffile
    - tornado
    - tzlocal
    - ujson

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - databroker

about:
  home: https://github.com/NSLS-II/databroker
  license: BSD
