{% set version = "3.14.12.4" %}
package:
    name: epics-base
    version: {{ version }}

source:
    fn: baseR{{ version }}.tar.gz
    url: http://www.aps.anl.gov/epics/download/base/baseR{{ version }}.tar.gz
    sha256: 0ea4a74e83ff73d68b64de89bedf7c42102edc2cc69c69fd49eb35c04dc9e3de
    patches:
        - config_site.diff
        - config_common.diff

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - readline 6.2*

  run:
    - readline 6.2*

about:
    home: http://www.aps.anl.gov/epics
    license: Epics Open License
    summary: EPICS Base Library
