package:
  name: csxtools
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'GGIT_STUB')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 'GIT_STUB') }}

source:
  git_url: https://github.com/NSLS-II-CSX/csxtools
  git_rev: master

build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}_np{{ np }}py{{ py }}

requirements:
  build:
    - setuptools
    - python
    - numpy x.x
    - pytest

  run:
    - python
    - numpy x.x
    - matplotlib
    - ipython
    - ipywidgets
    - databroker
    - metadatastore
    - pims >=0.3.3

test:
  requires:
    - pytest
    - nslsii_dev_configuration
  imports:
    - csxtools
    - csxtools.ext
    - csxtools.ext.fastccd
    - csxtools.ext.image
    - csxtools.ext.phocount

about:
  home: https://github.com/NSLS-II-CSX/csxtools
  license: BSD 3-clause
