package:
  name: humanize
  version: 0.5.1

source:
  git_rev: 0.5.1
  git_url: https://github.com/jmoiron/humanize

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - humanize

about:
  home: http://github.com/jmoiron/humanize
  license: MIT License
  summary: 'python humanize utilities'
