package:
  name: pcaspy
  version: 0.5.1

source:
  git_url: https://github.com/paulscherrerinstitute/pcaspy
  git_rev: 0.5.1

build:
  number: 2

requirements:
  build:
    - python
    - setuptools
    - epics-base
    - swig

  run:
    - python
    - epics-base

test:
  imports:
    - pcaspy

about:
  home: https://code.google.com/p/pcaspy/
  license: BSD