
package:
    name: pyepics
    version: {{ environ.get('GIT_DESCRIBE_TAG', 'GIT_STUB') }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 'GIT_STUB') }}

source:
    git_url: https://github.com/pyepics/pyepics.git
    git_rev: master

build:
    number: 0
    string: {{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}_py{{ py }}

requirements:
    build:
        - python
        - setuptools
        - numpy
        - epics-base
    run:
        - python
        - numpy
        - epics-base

test:
    imports:
        - epics
        - epics.pv

about:
    home: http://pyepics.github.io/pyepics/
    license: Epics Open License
    summary: Python interface to Epics Channel Access
