package:
  name: bluesky
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'GIT_STUB')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 'inf') }}

source:
  git_url: https://github.com/NSLS-II/bluesky
  git_rev: master

build:
  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}

requirements:
  build:
    - python

  run:
    - python
    - jsonschema
    - super_state_machine
    - numpy
    - metadatastore
    - filestore
    - matplotlib
    - prettytable
    - cycler
    - traitlets
    - historydict
    - lmfit
    - ipython


test:
  requires:
    - nslsii_dev_configuration
    - databroker
  imports:
    - 'bluesky'
    - 'bluesky.examples'
    - 'bluesky.callbacks'
    - 'bluesky.register_mds'
    - 'bluesky.standard_config'

about:
  home: https://github.com/NSLS-II/bluesky
  license: BSD
