{% set version = "2.6.0" %}

package:
    name: h5py
    version: {{ version }}

source:
    fn: h5py-{{ version }}.tar.gz
    url: https://github.com/h5py/h5py/archive/{{ version }}.tar.gz
    sha256: 7fec1d6f19418b3a624bbb90c7baa105952c0bb6cfbb6676f436fac44fc6ccfb

build:
    number: 0
    skip: True  # [py2k]
    script: HDF5_DIR={{ environ.PREFIX }} python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - cython
        - hdf5 >=1.10.0
        - pkgconfig
        - python
        - numpy
        - six

    run:
        - hdf5 >=1.10.0
        - numpy
        - python
        - six
        - unittest2  #[py26]

about:
    home: http://www.h5py.org/
    license: New BSD (http://opensource.org/licenses/bsd-license.php)
