{% set version = "0.1" %}

package:
    name: portable-fs
    version: {{ version }}

source:
    git_url: https://github.com/nsls-ii/portable-fs
    git_rev: v{{ version }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    skip: True   # [py2k]

requirements:
    build:
        - python
        - setuptools

    run:
        - doct
        - json
        - mongoquery
        - numpy
        - metadatastore
        - h5py
        - python
        - pytz
        - tzlocal
        - sqlite  
        
test:
    imports:
        - portable_fs

about:
    home: https://nsls-ii.github.io/portable-fs
    license: BSD 3-Clause
