{% set year = "2017" %}
{% set cycle = "01" %}

package:
  name: analysis
  version: {{ year }}_{{ cycle }}

build:
  number: 0

requirements:
  run:
    - album
    - amostra  # [py3k]
    - bluesky  # [py3k]
    - channelarchiver
    - databroker
    - datamuxer
    - ipywidgets
    - jupyter
    - lmfit ==0.8.3
    - matplotlib
    - openpyxl
    - pymongo
    - python
    - scikit-beam
    - suitcase
    - xray-vision
