{% set year = "18" %}
{% set cycle = "Q1" %}
{% set version ="0" %}

package:
  name: analysis
  version: {{ year }}{{ cycle }}.{{ version }}

build:
  number: 2

requirements:
  run:
    - amostra  # [py3k]
    - bluesky  # [py3k]
    - controls-doctor
    - dask
    - databroker
    - databroker-browser
    - datamuxer
    - distributed
    - ipython
    - ipywidgets
    - jupyter
    - openpyxl
    - pyqt >=5.6.0
    - oscars
    - python
    - qt >=5.6.0
    - scikit-beam
    - suitcase
    - sympy
    - xray-vision
