{% set year = "2018" %}
{% set cycle = "2" %}
{% set version ="0" %}

package:
  name: analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - amostra  # [py3k]
    - bluesky  # [py3k]
    - controls-doctor
    - dask
    - databroker
    - databroker-browser
    - datamuxer
    - distributed
    - fabio
    - graphviz
    - ipython
    - ipywidgets
    - jupyter
    - openpyxl
    - pyqt >=5.6.0
    - oscars
    - python
    - python-graphviz
    - qt >=5.6.0
    - scikit-beam
    - suitcase
    - sympy
    - xray-vision
