{% set year = "17" %}
{% set cycle = "Q1" %}
{% set version ="0" %}

package:
  name: analysis
  version: {{ year }}{{ cycle }}.{{ version }}

build:
  number: 2

requirements:
  run:
    - amostra ==0.2  # [py3k]
    - bluesky ==0.8.0  # [py3k]
    - channelarchiver
    - databroker ==0.7.0
    - datamuxer ==0.3.0
    - doct ==1.0.3
    - filestore ==0.7.0
    - historydict ==1.2.0
    - ipython ==5.1
    - ipywidgets ==5.2.2
    - jupyter
    - metadatastore ==0.6.4
    - metadataclient ==0.3.0  # [py3k]
    - openpyxl
    - pymongo
    - pyqt ==4.11.4
    - python ==3.5.1
    - suitcase ==0.5.2
    - scikit-beam ==0.0.9
    - xray-vision ==0.0.6
