{% set year = "2019" %}
{% set cycle = "2" %}
{% set version ="0" %}

package:
  name: analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 4

requirements:
  run:
    - amostra  # [py3k]
    - bluesky >=1.5.2  # [py3k]
    - bluesky-kafka  # [py3k]
    - controls-doctor
    - dask
    - databroker >=0.12.2
    - databroker-browser
    - datamuxer
    - distributed
    - event-model >=1.8.2
    - fabio
    - ffmpeg
    - flake8
    - graphviz
    - grid-strategy
    - h5py >=2.9.0
    - hdf5 =1.10.2
    - ipykernel
    - ipympl==0.1.1
    - ipython
    - ipywidgets==7.2.1
    - jupyter
    - matplotlib >3.0.1
    - numpy >=1.14.0
    - openpyxl
    - ophyd >=1.3.2
    - oscars
    - peakutils
    - pyfftw
    - pyqt >=5.6.0
    - python >=3.6.0
    - python-graphviz
    - qt >=5.6.0
    - scikit-beam
    - sympy
    - tornado <5.0.0
    - xlrd
    - xlwt
    - xray-vision
