package:
    name: lmfit
    version: {{ environ.get('GIT_DESCRIBE_TAG', 'GIT_STUB') }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 'inf') }}

source:
    git_url: https://github.com/lmfit/lmfit-py.git
    git_rev: master

build:
    number: 0
    string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}

requirements:
    build:
        - python
        - setuptools
        - numpy
        - scipy

    run:
        - python
        - numpy
        - scipy
        - ipywidgets

test:
    imports:
        - lmfit

about:
    home: http://lmfit.github.io/lmfit-py/
    license: BSD
