{% set year = "2018" %}
{% set cycle = "2" %}
{% set version ="0" %}

package:
  name: 28-id-2-xpd-analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - xpdan
    - bluesky
    - databroker
