package:
  name: suitcase
  version: {{ environ.GIT_DESCRIBE_TAG[1:] }}.post{{ environ.GIT_DESCRIBE_NUMBER }}

source:
  git_url: https://github.com/NSLS-II/suitcase.git
  git_rev: master

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six
    - databroker
    - h5py
    - numpy

test:
  requires:
    - nslsii_dev_configuration

  imports:
    - suitcase

about:
  home: http://github.com/nsls-ii/suitcase
  license: BSD 3-Clause

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
