package:
  name: event-model
version: {{ GIT_DESCRIBE_TAG }}.post{{ GIT_DESCRIBE_NUMBER }}

source:
  git_url: https://github.com/NSLS-II/event-model
  git_rev: master

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - event_model

about:
  home: https://github.com/NSLS-II/event_model
  license: BSD
