package:
  name: kiwisolver
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_rev: master
  git_url: https://github.com/nucleic/kiwi
  patches:
    - setup.py.patch

build:
  number: 1
  skip: True  # [py3k]

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/nucleic/kiwi
  license: Modified BSD
  summary: 'A fast implementation of the Cassowary constraint solver'
