package:
  name: pims
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'GIT_STUB')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 'GIT_STUB') }}

source:
  git_url: https://github.com/soft-matter/pims.git
  git_rev: master

build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}_py{{ py }}

requirements:
  build:
    - python
    - six
    - setuptools
    - slicerator >=0.9.7
    - numpy

  run:
    - python
    - six
    - slicerator >=0.9.7
    - numpy
    - scipy
    - pillow
    - tifffile

test:
  imports:
    - pims

about:
  home: http://soft-matter.github.io/pims/
  license: BSD
