package:
  name: pims
  version: {{ environ['GIT_DESCRIBE_TAG'][1:] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: https://github.com/soft-matter/pims.git
  git_rev: master

build:
  number: 0
  string: {{ environ['GIT_BUILD_STR'] }}_py{{ py }}

requirements:
  build:
    - python
    - six
    - setuptools
    - slicerator >=0.9.7
    - numpy

  run:
    - python
    - six
    - slicerator >=0.9.7
    - numpy
    - scipy
    - pillow
    - tifffile

test:
  imports:
    - pims

about:
  home: http://soft-matter.github.io/pims/
  license: BSD
