package:
  name: filestore
  version: {{ environ.GIT_DESCRIBE_TAG }}.post{{ environ.GIT_DESCRIBE_NUMBER }}

source:
  git_url: https://github.com/NSLS-II/filestore
  git_rev: master
  patches:
    - config.patch

build:
  number: 0

requirements:
  build:
    - python
    - six

  run:
    - python
    - h5py
    - six
    - pyyaml
    - jsonschema
    - pims
    - tifffile
    - boltons
    - pymongo
    - doct

test:
  imports:
    - filestore

about:
  home: https://github.com/NSLS-II/filestore
  license: BSD
