package:
  name: filestore
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../
  patches:
    - config.patch

build:
  number: 1

  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}


requirements:
  build:
    - python
    - six

  run:
    - python
    - h5py
    - numpy
    - six
    - pyyaml
    - jsonschema
    - pims
    - boltons
    - pymongo
    - doct

about:
  home: https://github.com/NSLS-II/filestore
  license: BSD
