{% set version = "0.9.0" %}

package:
    name: bluesky
    version: {{ version }}

source:
    git_url: https://github.com/nsls-ii/bluesky
    git_rev: v{{ version }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    skip: True  # [py2k]

requirements:
    build:
        - python

    run:
        - boltons
        - cycler
        - databroker
        - doct
        - event-model
        - filestore
        - historydict
        - jinja2
        - jsonschema
        - metadatastore
        - matplotlib
        - numpy
        - python
        - scipy
        - super_state_machine
        - tifffile
        - traitlets
        - xray-vision

test:
    requires:
        - nslsii_dev_configuration
        - databroker
        - pyepics
    imports:
        - bluesky

about:
    home: https://github.com/NSLS-II/bluesky
    license: BSD
