{% set version = "0.6.2" %}

package:
    name: bluesky
    version: {{ version }}

source:
    url: https://github.com/NSLS-II/bluesky/archive/v{{ version }}.tar.gz
    fn: bluesky-v{{ version }}.tar.gz
    sha256: 58b225cce55dd406347736b07e5af6b764d68be5d78e7129ccaec978ced9e9d6

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    skip: True  # [py2k]

requirements:
    build:
        - python

    run:
        - boltons
        - cycler
        - databroker
        - doct
        - event-model
        - filestore
        - historydict
        - jinja2
        - jsonschema
        - metadatastore
        - matplotlib
        - numpy
        - python
        - scipy
        - super_state_machine
        - tifffile
        - traitlets
        - xray-vision

test:
    requires:
        - nslsii_dev_configuration
        - databroker
        - pyepics
    imports:
        - bluesky

about:
    home: https://github.com/NSLS-II/bluesky
    license: BSD
