{% set version = "0.6.0" %}

package:
    name: bluesky
    version: {{ version }}

source:
    url: https://github.com/NSLS-II/bluesky/archive/v{{ version }}.tar.gz
    fn: bluesky-v{{ version }}.tar.gz
    sha256: 063046923781088805a09ac28fe11a7ad0c7b402e79201fc125b4f8484c0a201

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt
    skip: True  # [py2k]

requirements:
    build:
        - python

    run:
        - boltons
        - cycler
        - databroker
        - doct
        - event-model
        - filestore
        - historydict
        - jinja2
        - jsonschema
        - metadatastore
        - matplotlib
        - numpy
        - python
        - scipy
        - super_state_machine
        - tifffile
        - traitlets
        - xray-vision

test:
    requires:
        - nslsii_dev_configuration
        - databroker
        - pyepics
    imports:
        - bluesky

about:
    home: https://github.com/NSLS-II/bluesky
    license: BSD
