{% set name = "bluesky" %}
{% set version = "1.1.0" %}
{% set sha256 = "bf5467874716eca7741d8a95326317fa2ae3778c4211cb7b52588a830c62169e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/NSLS-II/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0 
  skip: True  # [py2k or osx]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - cycler
    - event-model
    - historydict
    - ipython
    - jsonschema
    - lmfit
    - matplotlib
    - numpy
    - super_state_machine
    - toolz
    - tqdm
    - pyzmq
    - doct

test:
  imports:
    - bluesky
    - bluesky.plans
    - bluesky.callbacks

about:
  home: https://github.com/NSLS-II/bluesky
  license: BSD-3-clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A Python data collection interface for experimental science'

  description: 'A Python data collection interface for experimental science'
  doc_url: http://nsls-ii.github.io/bluesky/
  dev_url: https://github.com/NSLS-II/bluesky

extra:
  recipe-maintainers:
    - CJ-Wright
