{% set version = "3.29.3" %}
# Copyright 2014-2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
    name: pygobject3
    version: {{ version }}

source:
    fn: pygobject-{{ version }}.tar.xz
    url: http://ftp.gnome.org/pub/GNOME/sources/pygobject/3.29/pygobject-{{ version }}.tar.xz
    sha256: a21eeff1d81061110625b1109d7f0b4b68a7518613892c259c6cec5687563dfc

build:
    number: 0
    detect_binary_files_with_prefix: true
    skip: True  # [py2k]

requirements:
    build:
        - cairo-gobject
        - glib
        - gobject-introspection
        - libffi
        - py2cairo # [py2k]
        - py3cairo # [py3k]
        - python
    run:
        - cairo-gobject
        - glib
        - gobject-introspection
        - libffi
        - py2cairo # [py2k]
        - py3cairo # [py3k]
        - python

about:
    home: http://www.gtk.org/
    license: LGPL
    summary: Access to GObject-based libraries in Python.
