
package:
    name: service_identity
    version: "14.0.0"

source:
  git_url: https://github.com/pyca/service_identity
  git_rev: 14.0.0

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - pyopenssl
        - pyasn1
        - pyasn1-modules
        - characteristic
    run:
        - python
        - pyopenssl
        - pyasn1
        - pyasn1-modules
        - characteristic

test:
    imports:
        - service_identity

about:
    home: https://github.com/pyca/service_identity
    license: MIT
    summary: Service identity verification for pyOpenSSL
